import '../models/book_model.dart';
import '../models/user_model.dart';

class DemoConfig {
  static const bool isDemoMode = true;
  
  static final UserModel demoUser = UserModel(
    id: 'demo_user_1',
    email: 'demo@igitabu.com',
    displayName: 'Demo User',
    role: UserRole.reader,
    createdAt: DateTime.now().subtract(const Duration(days: 30)),
    updatedAt: DateTime.now(),
  );

  static final UserModel demoAuthor = UserModel(
    id: 'demo_author_1',
    email: 'author@igitabu.com',
    displayName: 'Demo Author',
    role: UserRole.author,
    createdAt: DateTime.now().subtract(const Duration(days: 60)),
    updatedAt: DateTime.now(),
  );

  static final List<BookModel> demoBooks = [
    BookModel(
      id: 'book_1',
      title: 'Ubwiyunge bw\'Uburundi',
      description: 'Igitabo kivuga ku mateka y\'Uburundi n\'ubwiyunge bwayo.',
      authorId: 'demo_author_1',
      authorName: 'Demo Author',
      genre: 'History',
      language: 'Kirundi',
      price: 0.0,
      pdfUrl: 'https://example.com/book1.pdf',
      publishedAt: DateTime.now().subtract(const Duration(days: 10)),
      createdAt: DateTime.now().subtract(const Duration(days: 10)),
      updatedAt: DateTime.now().subtract(const Duration(days: 10)),
      downloadCount: 150,
      rating: 4.5,
      reviewCount: 23,
      tags: ['history', 'burundi', 'culture'],
    ),
    BookModel(
      id: 'book_2',
      title: 'Flutter Development Guide',
      description: 'A comprehensive guide to building mobile apps with Flutter.',
      authorId: 'demo_author_1',
      authorName: 'Demo Author',
      genre: 'Education',
      language: 'English',
      price: 19.99,
      pdfUrl: 'https://example.com/book2.pdf',
      publishedAt: DateTime.now().subtract(const Duration(days: 5)),
      createdAt: DateTime.now().subtract(const Duration(days: 5)),
      updatedAt: DateTime.now().subtract(const Duration(days: 5)),
      downloadCount: 89,
      rating: 4.8,
      reviewCount: 12,
      tags: ['flutter', 'programming', 'mobile'],
    ),
    BookModel(
      id: 'book_3',
      title: 'Contes du Burundi',
      description: 'Une collection de contes traditionnels burundais.',
      authorId: 'demo_author_1',
      authorName: 'Demo Author',
      genre: 'Fiction',
      language: 'French',
      price: 5.99,
      pdfUrl: 'https://example.com/book3.pdf',
      publishedAt: DateTime.now().subtract(const Duration(days: 15)),
      createdAt: DateTime.now().subtract(const Duration(days: 15)),
      updatedAt: DateTime.now().subtract(const Duration(days: 15)),
      downloadCount: 67,
      rating: 4.2,
      reviewCount: 8,
      tags: ['contes', 'tradition', 'burundi'],
    ),
    BookModel(
      id: 'book_4',
      title: 'Amashusho y\'Ubwoba',
      description: 'Igitabo cy\'amashusho agira ubwoba n\'amatsiko.',
      authorId: 'demo_author_1',
      authorName: 'Demo Author',
      genre: 'Poetry',
      language: 'Kirundi',
      price: 0.0,
      pdfUrl: 'https://example.com/book4.pdf',
      publishedAt: DateTime.now().subtract(const Duration(days: 20)),
      createdAt: DateTime.now().subtract(const Duration(days: 20)),
      updatedAt: DateTime.now().subtract(const Duration(days: 20)),
      downloadCount: 234,
      rating: 4.7,
      reviewCount: 45,
      tags: ['poetry', 'kirundi', 'emotions'],
    ),
    BookModel(
      id: 'book_5',
      title: 'Children\'s Stories',
      description: 'Fun and educational stories for children.',
      authorId: 'demo_author_1',
      authorName: 'Demo Author',
      genre: 'Children',
      language: 'English',
      price: 3.99,
      pdfUrl: 'https://example.com/book5.pdf',
      publishedAt: DateTime.now().subtract(const Duration(days: 8)),
      createdAt: DateTime.now().subtract(const Duration(days: 8)),
      updatedAt: DateTime.now().subtract(const Duration(days: 8)),
      downloadCount: 156,
      rating: 4.9,
      reviewCount: 67,
      tags: ['children', 'education', 'stories'],
    ),
  ];
}